### ISSUE TITLE
Getting [] values in horoscope

### ISSUE THREAD

**Issue by ghost** [tapaswenipathak/Horoscope-API#11]
From last two days, all urls from your API's are returning only [] values. I checked them in browser and REST Client, but same result.

**Comment by anshdiv** [comment]
Null values return from all urls,Please fix it ASAP

**Comment by SereneRoc** [comment]
Only receiving null values as well.

**Comment by tapaswenipathak** [comment]
Commit d8e5bfb resolves this. Closing the issue.
