### ISSUE TITLE
API not working as of 28th August 2016

### ISSUE THREAD

**Issue by knight-rider1609** [tapaswenipathak/Horoscope-API#13]
Eg: http://horoscope-api.herokuapp.com/horoscope/week/virgo  
returns
{
  "horoscope": "[]", 
  "sunsign": "virgo", 
  "week": "[]"
}

**Comment by stoyandim** [comment]
Have the same issue, not working for like 2 days now.

**Comment by vanthang91** [comment]
Same here, hope it will be fixed soon

**Comment by angien** [comment]
Still down 8/31. Hope it gets fixed soon as well!
