### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by waliente** [tapaswenipathak/Horoscope-API#15]
Hi when i try to make a get to horoscope service i have this message: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Maybe ihave to set some CORS? Or it's free make the callto your service?

**Comment by tapaswenipathak** [comment]
I am able to call it using [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm). If you share more information of how and from where are you trying to call, I will try to help.

**Comment by tapaswenipathak** [comment]
Please reopen if issue persist.
