### ISSUE TITLE
Could you please share the source for the heroku hosted code that actually does the GaneshaSpeaks calls?

### ISSUE THREAD

**Issue by gouravd** [tapaswenipathak/Horoscope-API#16]
Could you please share the source for the heroku hosted code that actually does the GaneshaSpeaks calls?

**Comment by tapaswenipathak** [comment]
Horoscope-API is using [pyhoroscope](https://github.com/tapasweni-pathak/pyhoroscope) package. This repository has all the code for Heroku.

Closing this, reopen if needed.
