### ISSUE TITLE
horoscope API: Internal Server Error

### ISSUE THREAD

**Issue by prashant10153** [tapaswenipathak/Horoscope-API#2]
Hi,

I am trying to use your API to add the feature in my site to get daily and weekly and yearly horoscope. But, I am getting an error.

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Below is the code I am using to get the data.

url = "http://horoscope-api.herokuapp.com/horoscope/week/libra";
$ch = curl_init();

curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); //Set curl to return the data instead of printing it to the browser.
curl_setopt($ch, CURLOPT_URL, $url);

$data = curl_exec($ch);
curl_close($ch);

print "<pre>";
print_r($data);
print "</pre>";

Can you please put some light, on the same and resolve the issue.

Thanks and Regards,

Prashant
09820035912

**Comment by mrxinu** [comment]
I'm getting the same error.

**Comment by tapaswenipathak** [comment]
Hey @prashant10153 @mrxinu The structural change in the website, that the package, this API uses, caused the issue. Sorry it took me some time to fix it. Now this is fixed, the [new version of pyhoroscope](https://github.com/tapasweni-pathak/pyhoroscope/releases) fixes this API. 

So, I'm closing this issue.
