### ISSUE TITLE
GET API not working

### ISSUE THREAD

**Issue by vnathv** [tapaswenipathak/Horoscope-API#32]
Below GET API is not working fine,

http://horoscope-api.herokuapp.com/horoscope/today/{Sign}

It is simply hitting a timeout

Thanks,
Vijay

**Comment by androidtutorialsrkt** [comment]
Still not working!

**Comment by tapaswenipathak** [comment]
Closed with c187d5ff8a62b7422cab699ed770cc2c6657ae47.
