### ISSUE TITLE
API NOT WORKING

### ISSUE THREAD

**Issue by androidtutorialsrkt** [tapaswenipathak/Horoscope-API#33]
Not receiving any response from API. Kindly check and resolved.

**Comment by claytron5000** [comment]
Fun toy, I'd love to use it for an in-house application.

**Comment by sumitgohil** [comment]
You can check this in case this is not working.

https://github.com/sumitgohil/horoscope-api/tree/master

**Comment by tapaswenipathak** [comment]
Closed with c187d5ff8a62b7422cab699ed770cc2c6657ae47.
