### ISSUE TITLE
Access-Control-Allow-Origin -- issue

### ISSUE THREAD

**Issue by ritsrivastava01** [tapaswenipathak/Horoscope-API#34]
I tried to hit your api from my application, but its through the error: 
Failed to load http://horoscope-api.herokuapp.com/horoscope/today/aries: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'localhost//4200' (OR website address) is therefore not allowed access.
I think you need to add CROS file to your root folder and  set 'Access-Control-Allow-Origin' : true;

**Comment by pratik-pdw** [comment]
Yeah Please include 'Access-Control-Allow-Origin' header on the response that you send

**Comment by damonsomu** [comment]
+1

**Comment by damonsomu** [comment]
This isn't sorted out till now. :(

**Comment by tapaswenipathak** [comment]
I have added a commit, feel free to reopen the ticket if you still see the error.
