### ISSUE TITLE
Requesting daily Horoscope

### ISSUE THREAD

**Issue by cub1960** [tapaswenipathak/Horoscope-API#36]
I am using the API for a chatbot - works great!  One issue though - I just requested the daily horoscope for today 6/5/2018.  I got the horoscope back but the date on the JSON response was 6/6/2018 - tomorrow.  I am in the US.  Is there anyway to get the correct one for today based on where I live?  Otherwise this will be useless since everytime somebody requests a horoscope here it will be tomorrow not today.

Could there be a way we can request by date?  That would solve it.  Thanks for the help love the API except this issue if there is someway to get today's on today.

**Comment by tapasweni-pathak** [comment]
@cub1960 can you check now? does it give you correct results?

**Comment by tapasweni-pathak** [comment]
@cub1960 can you check once now? does the call give you the correct results now?

**Comment by tapasweni-pathak** [comment]
@cub1960 can you check once now? does the call give you the correct results?

**Comment by tapaswenipathak** [comment]
@cub1960 can you check once now?

**Comment by sudheerkaushik** [comment]
+1 to daily updation.

Moreover, I would suggest to make a board where collaborators like me can update Horoscope by themselves.

**Comment by tapaswenipathak** [comment]
@SudhirKaushik Are you not getting daily horoscope? What is your timezone? 

> Moreover, I would suggest to make a board where collaborators like me can update Horoscope by themselves.

I didn't quiet get what you mean here. Do you want a POST API call to post horoscope and get what you POST?

**Comment by sudheerkaushik** [comment]
Yes, something like that. I have not checked yet whether horoscope is getting updated daily, I am about to use this in my app. Are they getting updated on daily basis?

No, there is nothing wrong with APIs, everything working just fine. Timezone is Kolkata GMT +05:30

**Comment by tapaswenipathak** [comment]
Please go ahead and check if you are getting daily updates, let me know on this ticket or another ticket if you don't.
