### ISSUE TITLE
Sagittarius in test.py

### ISSUE THREAD

**Issue by vivchik1337** [tapaswenipathak/Horoscope-API#40]
You have mistake in test.py with sign "sagittarius". Change please, because people who don't know that sagittarius is correct could have problems with that.

**Comment by tapaswenipathak** [comment]
🔍 Feel free to PR from next time, I have added a commit for now.

**Comment by tapaswenipathak** [comment]
🔍Feel free to PR for such things when you work on open source projects, I have added a commit for now.
