### ISSUE TITLE
java.io.Exception: ClearText http traffic

### ISSUE THREAD

**Issue by auben2k** [tapaswenipathak/Horoscope-API#42]
I am attempting to use this API as apart of my final project for my android development course. I am running into an issue when requesting horoscopes. Screenshots below. Please get back to me, thanks!

![image](https://user-images.githubusercontent.com/1340359/56042315-c18ee600-5d08-11e9-9eff-0172cd65c430.png)

**Comment by tapaswenipathak** [comment]
Did you Google this?
