### ISSUE TITLE
Tauras returning no data, no error

### ISSUE THREAD

**Issue by sudheerkaushik** [tapaswenipathak/Horoscope-API#43]
For all sunsign I am getting data but not for Tauras. Also, no API error in console

![image](https://user-images.githubusercontent.com/8871502/56091342-bad4b000-5e7b-11e9-8cf0-b7bd280a6873.png)

![image](https://user-images.githubusercontent.com/8871502/56091347-c9bb6280-5e7b-11e9-82ce-ee289fbb7275.png)

**Comment by TheBotBox** [comment]
You've made a typo. 
**taurus** instead of <i>tauras</i>

http://horoscope-api.herokuapp.com/horoscope/today/TAURUS

**Comment by tapaswenipathak** [comment]
Thanks, closing.

**Comment by sudheerkaushik** [comment]
My bad. Thanks for quick reply.

made something using this, still in development. Checkout : https://github.com/SudhirKaushik/Zodiac

**Comment by akshayrupareliya0912** [comment]
![image](https://user-images.githubusercontent.com/82557383/147317201-ff0a6bd0-9492-4683-8072-74b95c83bacf.png)
