### ISSUE TITLE
Server Encountered an Error

### ISSUE THREAD

**Issue by zak123** [tapaswenipathak/Horoscope-API#5]
:(

http://horoscope-api.herokuapp.com/horoscope/week/libra

http://i.imgur.com/F9IQbyL.png

**Comment by tapaswenipathak** [comment]
working on fixing it.

**Comment by anshdiv** [comment]
Please fix it ASAP... can u estimate how much time you take for fixing...

**Comment by tapaswenipathak** [comment]
Done. Thanks for the patience.

**Comment by anshdiv** [comment]
Thank you very much...now it working...
